name: mx_assets_obfuscate
description: obfuscate flutter image assets
version: 1.0.1
repository: https://github.com/MagicalWater/mx_assets_obfuscate

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  image_compression: ^1.0.4
  args: ^2.4.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  mx_assets_obfuscate: