name: mx_assets_obfuscate
description: obfuscate flutter image assets
version: 1.1.0
repository: https://github.com/MagicalWater/mx_assets_obfuscate

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  image_compression: ^1.0.5
  args: ^2.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8

executables:
  mx_assets_obfuscate: